---
- name: Rocketpool host base provisioning (security, users and dependencies)
  hosts: miners
  become: yes
  tasks:
# SECURE THE HOST
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Secure shared memory
      mount:
        src: none
        path: /run/shm
        fstype: tmpfs
        opts: defaults,ro
        state: mounted

    - import_role:
        name: jnv.unattended-upgrades
      vars:
        unattended_remove_unused_dependencies: true
        unattended_automatic_reboot: true
        unattended_automatic_reboot_time: "02:00"
        # unattended_mail: 'root@example.com'

    - import_role:
        name: dev-sec.ssh-hardening
  
    - import_role:
        name: dev-sec.os-hardening
      vars:
        sysctl_overwrite:
          # Enable IPv4 traffic forwarding. (for docker)
          net.ipv4.ip_forward: 1

# CREATE USERS
    - name: Add users
      user:
        name: "{{ item }}"
        shell: /bin/bash
      with_items:
      - admin
      - rp

    - name: Allow admin to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%admin'
        line: '%admin ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

# INSTALL DEPS
    # Needed for ansible to become unpriviledge user (see: https://github.com/georchestra/ansible/issues/55#issuecomment-588313638)
    - name: Install Access Control Lists (acl)
      apt:
        name: acl
        state: present

    - import_role:
        name: geerlingguy.ntp

    - import_role:
        name: geerlingguy.docker
      vars:
        docker_users:
        - admin
        - rp
  
# SETUP FIREWALL
    - name: Install The Uncomplicated Firewall (ufw)
      apt:
        name: ufw
        state: present
    - name: Deny incoming and enable UFW
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny    
    - name: Allow SSH
      community.general.ufw:
        state: enabled
        rule: allow
        name: OpenSSH
    - name: Allow ETH2 (port 9001)
      community.general.ufw:
        rule: allow
        port: 9001

    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
    - name: Add fail2ban sshd configuration
      ini_file:
        path: /etc/fail2ban/jail.d/ssh.conf
        section: "sshd"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: "enabled", value: "true" }
        - { option: "banaction", value: "ufw" }
        - { option: "port", value: "22" }
        - { option: "filter", value: "sshd" }
        - { option: "logpath", value: "%(sshd_log)s" }
        - { option: "maxretry", value: "5" }
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
