---
- name: Rocketpool host base provisioning (security, users and dependencies)
  hosts: miners
  become: yes
  tasks:
# SECURE THE HOST
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Secure shared memory
      mount:
        src: none
        path: /run/shm
        fstype: tmpfs
        opts: defaults,ro
        state: mounted

    - import_role:
        name: jnv.unattended-upgrades
      vars:
        unattended_remove_unused_dependencies: true
        unattended_automatic_reboot: true
        unattended_automatic_reboot_time: "02:00"
        # unattended_mail: 'root@example.com'

    - import_role:
        name: dev-sec.ssh-hardening
  
    - import_role:
        name: dev-sec.os-hardening
      vars:
        sysctl_overwrite:
          # Enable IPv4 traffic forwarding. (for docker)
          net.ipv4.ip_forward: 1

# SETUP FIREWALL
    - name: Install The Uncomplicated Firewall (ufw)
      apt:
        name: ufw
        state: present
    - name: Deny incoming and enable UFW
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny
    - name: Allow SSH, ETH1 and ETH2
      community.general.ufw:
        state: enabled
        rule: allow
        port: "{{ item }}"
      with_items:
        - 22
        - 40404
        - 10002

# CREATE USER
    - name: Create rocketpool user "rp"
      user:
        name: rp
        shell: /bin/bash

# INSTALL DEPS
    # Needed for ansible to become unprivileged user (see: https://github.com/georchestra/ansible/issues/55#issuecomment-588313638)
    - name: Install Access Control Lists (acl)
      apt:
        name: acl
        state: present

    # Needed by rocketpool installer
    - name: Install curl
      apt:
        name: curl
        state: present
    
    - name: Install chrony
      apt:
        name: chrony
        state: present

    - import_role:
        name: geerlingguy.docker
      vars:
        docker_users:
        - ted
        - rp
  
    - name: Install fail2ban
      apt:
        name: fail2ban
        state: present
    - name: Add fail2ban sshd configuration
      ini_file:
        path: /etc/fail2ban/jail.d/ssh.conf
        section: "sshd"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: "enabled", value: "true" }
        - { option: "banaction", value: "ufw" }
        - { option: "port", value: "22" }
        - { option: "filter", value: "sshd" }
        - { option: "logpath", value: "%(sshd_log)s" }
        - { option: "maxretry", value: "5" }
    - name: Restart fail2ban
      service:
        name: fail2ban
        state: restarted
