- name: Install and setup Rocket Pool
  hosts: miners
  become: yes
  become_user: rp
  tasks:
    - file:
        state: directory
        path: ~/bin
    - name: Download Rocket Pool binary
      get_url:
        url: https://github.com/rocket-pool/smartnode-install/releases/download/{{ rocket_pool.version }}/rocketpool-cli-linux-amd64
        dest: ~/bin/rocketpool
        mode: u=rwx,g=rx,o=rx
    - name: Install rocketpool
      shell: "~/bin/rocketpool service install -d -y"
    - name: Configure Rocket Pool
      blockinfile:
        path: ~/.rocketpool/settings.yml
        create: yes
        block: |
          chains:
            eth1:
              client:
                selected: infura
                params:
                - env: INFURA_PROJECT_ID
                  value: "{{ rocket_pool.eth1.infura_project_id }}"
                - env: ETHSTATS_LABEL
                  value: ""
                - env: ETHSTATS_LOGIN
                  value: ""
                - env: GETH_CACHE_SIZE
                  value: ""
                - env: GETH_MAX_PEERS
                  value: ""
                - env: ETH1_P2P_PORT
                  value: ""
                - env: PROVIDER_URL
                  value: ""
            eth2:
              client:
                selected: prysm
                params:
                - env: CUSTOM_GRAFFITI
                  value: "{{ rocket_pool.eth2.custom_graffiti }}"
                - env: ETH2_MAX_PEERS
                  value: ""
                - env: ETH2_P2P_PORT
                  value: "9001"
    - name: Set the eth2 client data path
      lineinfile:
        path: ~/.rocketpool/docker-compose.yml
        regexp: '^(.*)(?:eth2clientdata)(:/ethclient)'
        line: "\\1{{ rocket_pool.eth2.client_data_path }}\\2"
        backrefs: yes
#    - name: Start Rocket Pool service
#      shell: ~/bin/rocketpool service start

#    - name: TODO - wait for eth1 and eth2 to be in sync
#      shell: echo "TODO - wait for eth1 & eth2"
#    - name: TODO - Init wallet (rocketpool wallet init)
#      shell: echo "TODO - rocketpool wallet recover --password <the-password> --mnemonic <mnemonic>"