- name: Install and setup Rocket Pool, geth pruning and monitoring
  hosts: miners
  become: yes
  become_user: rp
  tasks:
    - file:
        state: directory
        path: ~/bin
    - name: Download Rocket Pool binary
      get_url:
        url: https://github.com/rocket-pool/smartnode-install/releases/download/{{ rocket_pool.version }}/rocketpool-cli-linux-amd64
        dest: ~/bin/rocketpool
        mode: u=rwx,g=rx,o=rx
    - name: Install rocketpool
      shell: "~/bin/rocketpool service install -d -y -v {{ rocket_pool.version }}"
    - name: Configure Rocket Pool
      blockinfile:
        path: ~/.rocketpool/settings.yml
        create: yes
        block: |
          chains:
            eth1:
              client:
                selected: geth
                params:
                - env: ETH1_P2P_PORT
                  value: "40404"
            eth2:
              client:
                selected: prysm
                params:
                - env: ETH2_P2P_PORT
                  value: "10002"

    - name: Set the eth1 client data path
      lineinfile:
        path: ~/.rocketpool/docker-compose.yml
        regexp: '^(.*)(?:eth1clientdata)(:/ethclient)'
        line: "\\1{{ rocket_pool.eth1.client_data_path }}\\2"
        backrefs: yes

    - name: Set the eth2 client data path
      lineinfile:
        path: ~/.rocketpool/docker-compose.yml
        regexp: '^(.*)(?:eth2clientdata)(:/ethclient)'
        line: "\\1{{ rocket_pool.eth2.client_data_path }}\\2"
        backrefs: yes

    - name: Configure Prysm beacon with fallback web3 provider
      lineinfile:
        path: ~/.rocketpool/chains/eth2/start-beacon.sh
        regexp: '^(.*\/app\/cmd\/beacon-chain\/beacon-chain )(?:--fallback-web3provider=\S* )?(.*)'
        line: "\\1--fallback-web3provider={{ rocket_pool.eth1.fallback_web3provider }} \\2"
        backrefs: yes

    - name: Copy geth prune script
      copy:
        src: ./prune_geth.sh
        dest: /home/rp/bin/
        mode: preserve

    - name: "Schedule monthly geth pruning"
      cron:
        name: "geth pruning"
        minute: "0"
        hour: "0"
        day: "1"
        user: "rp"
        job: "/home/rp/bin/prune_geth.sh"

    - name: Copy monitoring docker stack
      copy:
        src: ./monitoring/
        dest: /home/rp/rocketpool_monitoring/
        mode: preserve

    - name: Configue geth for Prometheus monitoring
      lineinfile:
        path: ~/.rocketpool/chains/eth1/start-node.sh
        regexp: '^(.*\/usr\/local\/bin\/geth )(?:--metrics --pprof --pprof.addr \d+\.\d+\.\d+\.\d+ )?(.*)'
        line: "\\1--metrics --pprof --pprof.addr 0.0.0.0 \\2"
        backrefs: yes

    - name: Configure Prysm beacon for Prometheus monitoring
      lineinfile:
        path: ~/.rocketpool/chains/eth2/start-beacon.sh
        regexp: '^(.*\/app\/cmd\/beacon-chain\/beacon-chain )(?:--monitoring-host \d+\.\d+\.\d+\.\d+ )?(.*)'
        line: "\\1--monitoring-host 0.0.0.0 \\2"
        backrefs: yes
    - name: Configure prysm beacon for Prometheus monitoring continued...
      lineinfile:
        path: ~/.rocketpool/chains/eth2/start-beacon.sh
        regexp: '^(.*CMD)(?: --disable-monitoring)(.*)'
        line: "\\1\\2"
        backrefs: yes

    - name: Configure Prysm validator for Prometheus monitoring
      lineinfile:
        path: ~/.rocketpool/chains/eth2/start-validator.sh
        regexp: '^(.*/app/cmd/validator/validator )(?:--monitoring-host \d+\.\d+\.\d+\.\d+ )?(.*)'
        line: "\\1--monitoring-host 0.0.0.0 \\2"
        backrefs: yes

    - name: Start Rocket Pool service
      shell: ~/bin/rocketpool service start

    #- name: Start the monitoring stack
    #  shell: docker-compose -f rocketpool_monitoring/docker-compose.yaml up -d --build --remove-orphans
    #  args: 
    #    chdir: /home/rp

#    - name: TODO - wait for eth1 and eth2 to be in sync
#      shell: echo "TODO - wait for eth1 & eth2"
#    - name: TODO - Init wallet (rocketpool wallet init)
#      shell: echo "TODO - rocketpool wallet recover --password <the-password> --mnemonic <mnemonic>"