version: "3.8"
services:
  
  prometheus:
    restart: "unless-stopped"
    build:
      context: ./prometheus
    volumes:
      - /var/lib/fast/config/logging/prometheus/:/prometheus
    depends_on:
      - node-exporter
      - blackbox-exporter
      - json-exporter
      - cryptowat-exporter

  node-exporter:
    restart: "unless-stopped"
    image: prom/node-exporter

  blackbox-exporter:
    restart: "unless-stopped"
    build:
        context: ./blackbox
    command:
      - --config.file=/config/blackbox.yml
  
  json-exporter:
    restart: "unless-stopped"
    build:
        context: ./json
  
  cryptowat-exporter:
    restart: "unless-stopped"
    image: nbarrientos/cryptowat_exporter
    environment:
      - CRYPTOWAT_EXCHANGES=kraken
      - CRYPTOWAT_PAIRS=ethusd,ethchf
      - CRYPTOWAT_CACHESECONDS=300
      - TZ=Europe/Zurich
  
  grafana:
    restart: "unless-stopped"
    build:
      context: ./grafana
    image: rpool-grafana
    volumes:
      - /var/lib/fast/config/logging/grafana/:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000/tcp

networks:
  default:
    external:
      name: rocketpool_net