version: "3.8"
services:
  
  prometheus:
    restart: "unless-stopped"
    build:
      context: ./prometheus
    volumes:
      - /var/lib/fast/config/logging/prometheus/:/prometheus
    depends_on:
      - node-exporter
      - blackbox-exporter

  node-exporter:
    restart: "unless-stopped"
    image: prom/node-exporter
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.textfile.directory=/host/textfile_collector"
    volumes:
      - /proc:/host/proc:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /var/lib/node_exporter/textfile_collector:/host/textfile_collector:ro

  blackbox-exporter:
    restart: "unless-stopped"
    build:
        context: ./blackbox
    command:
      - --config.file=/config/blackbox.yml
  
  grafana:
    restart: "unless-stopped"
    build:
      context: ./grafana
    image: rpool-grafana
    volumes:
      - /var/lib/fast/config/logging/grafana/:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000/tcp

networks:
  default:
    external:
      name: rocketpool_net