---
- name: Copy monitoring docker stack
  copy:
    src: ./
    dest: /home/rp/rocketpool_monitoring/

- name: Configure Prysm beacon for Prometheus monitoring
  lineinfile:
    path: ~/.rocketpool/chains/eth2/start-beacon.sh
    regexp: '^(.*/app/cmd/beacon-chain/beacon-chain )(?:(--.* )?(--monitoring-host \d+\.\d+\.\d+\.\d+ ))?((--.* )?--accept-terms-of-use.*)'
    line: "\\1\\2--monitoring-host 0.0.0.0 \\4"
    backrefs: yes

- name: Configure Prysm validator for Prometheus monitoring
  lineinfile:
    path: ~/.rocketpool/chains/eth2/start-validator.sh
    regexp: '^(\s*exec /app/cmd/validator/validator )(?:(--.* )?(--monitoring-host \d+\.\d+\.\d+\.\d+ ))?((--.* )?--accept-terms-of-use.*\")'
    line: "\\1\\2--monitoring-host 0.0.0.0 \\4"
    backrefs: yes

# TODO: somehow check if there where any changes made to the startupscripts and only restart if that's the case.
- name: Restart rocketpool to apply new settings
  shell: ~/bin/rocketpool s p -y; ~/bin/rocketpool s s

- name: Start the monitoring stack
  shell: docker-compose -f rocketpool_monitoring/docker-compose.yaml up -d --build --remove-orphans
  args: 
    chdir: /home/rp
