FROM prom/prometheus

COPY ./prysm-prom.yml /etc/prometheus/prometheus.yml

#CMD ["/bin/prometheus", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles", "--config.file=/etc/prometheus/prysm-prom.yml"]
